# Generated by Django 5.2.8 on 2026-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_approval_date_customuser_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spam_reasons',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spam_score',
            field=models.IntegerField(default=0),
        ),
    ]
