# Generated by Django 5.2.8 on 2025-11-26 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books & Supplies'), ('jewelry', 'Jewelry & Accessories'), ('keys', 'Keys & ID Cards'), ('bags', 'Bags & Backpacks'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('location_found', models.CharField(max_length=200)),
                ('date_found', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
