# Generated by Django 5.2.8 on 2025-12-05 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_discard_date_item_discard_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approval_date',
            field=models.DateTimeField(blank=True, help_text='Date when item was approved and received', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from staff about receiving the item'),
        ),
        migrations.AddField(
            model_name='item',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who approved/received the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported - Pending Verification'), ('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('rejected', 'Rejected Claim'), ('verified', 'Verified'), ('returned', 'Returned'), ('discarded', 'Discarded / Donated')], default='reported', max_length=20),
        ),
    ]
