# Generated by Django 5.2.8 on 2025-12-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_approval_date_item_approval_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='items/default.jpg', upload_to='items/'),
        ),
    ]
