# Generated by Django 5.2.8 on 2026-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_item_verified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='item',
            name='spam_reasons',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='spam_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='submitter_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
